---
# tasks file for galaxy-caddy

- name: Download Caddy DEB
  get_url:
    url: https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_{{ caddy_arch }}.deb
    dest: /tmp/caddy_{{ caddy_version }}_linux_{{ caddy_arch }}.deb
    checksum: sha512:https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_checksums.txt
  check_mode: false

# TODO: cache checksum file

- name: Install Caddy
  apt:
    deb: /tmp/caddy_{{ caddy_version }}_linux_{{ caddy_arch }}.deb


- name: Create caddy needed directories
  file: path={{ item }}
        state=directory
        owner=caddy
  with_items:
    - "{{ caddy_confd }}"

- name: Caddyfile
  template: src=caddyfile.j2
            dest={{ caddy_conf }}/Caddyfile
  notify: reload caddy

- name: Configure reverse proxy sites
  template:
    src: reverse_proxy.caddy.j2
    dest: "{{ caddy_confd }}/reverse_proxy.caddy"
    owner: caddy
    group: caddy
  notify: reload caddy
