---
# handlers file for galaxy-caddy

- name: start caddy
  service: name=caddy
           state=started
           enabled=yes
           daemon_reload=yes

- name: reload caddy
  service: name=caddy
           state=reloaded
           enabled=yes
